version: '3.7'

services:
  app:
    image: cjreysayago/simple-laravel
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    links:
      - db
      - testdb
    environment:
      APACHE_RUN_USER: apache # Start service with the given user
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
  testdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
