version: '3.7'

services:
  app:
    image: cjreysayago/laravel-env
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    links:
      - testdb
  testdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test