version: '3.7'

services:
  app:
    image: cjreysayago/laravel-env
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    links:
      - db
      - testdb
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
  testdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
